sudo: required
services: 
  - docker

env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10-jessie

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

stages:
  - test
  - npm-targets 

jobs:
  include:
    -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=test
    -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=lint
   -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=8-jessie
        - NPM_TARGET=coverage
    -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=test
    -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=lint
   -stage: npm-targets
    name: "Test 8-jessie"
    install: skip
    script:
      - docker run --rm $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET
      env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=coverage